Repository malcommac/Repeat, pull requests merged in 2018-03, with the labels that each got.

#9 fix cocoapods installation instructions
  README.md
Labels: documentation

#4 Fix indentation in README.md
  README.md
Labels: documentation

#12 Ignores SPM build artifacts and Xcode user settings.
  .gitignore
Labels: enhancement

#10 fix typo in variable name
  Sources/Repeat/Repeater.swift
Labels: documentation, enhancement

#11 Support for restarting `.once` Timer
  Sources/Repeat/Repeater.swift
  Tests/RepeatTests/RepeatTests.swift
Labels: bug, enhancement

#14 Refactors equatable implementation to use an identity operator
  Sources/Repeat/Repeater.swift
  Tests/RepeatTests/RepeatTests.swift
Labels: enhancement
